---

version: '3.4'

services:
  ups-metrics_runner:
    image: docker-registry.localnet:5000/ups-metrics_runner
    build: ./ups-metrics_runner
    environment:
     - SNMP_ADDRESS=10.0.1.213
     - ELASTIC_URL=https://elasticsearch.local:9200
     - ELASTIC_INDEX=power
     - DEBUG=True
